src/Entity/Formation.php
<?php

namespace App\Entity;
use App\Entity\Produit;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbres_heures;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement;
        /**
     * @ORM\ManyToOne(targetEntity="Produit")
     * @ORM\JoinColumn()
     */
    private $produit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getNbresHeures(): ?int
    {
        return $this->nbres_heures;
    }

    public function setNbresHeures(int $nbres_heures): self
    {
        $this->nbres_heures = $nbres_heures;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut')
            ->add('nbres_heures')
            ->add('departement')
            ->add('produit', EntityType::class, array(
                'class' => 'App\Entity\Produit',
                'choice_label' => 'libelle',
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Entity\Inscription;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formation")
 */
class FormationController extends AbstractController
{
    /**
     * @Route("/", name="formation_index", methods={"GET"})
     */
    public function index(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="formation_show", methods={"GET"})
     */
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="formation_delete", methods={"POST"})
     */
    public function delete(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            
            $inscriptions = $this->getDoctrine()->getRepository(Inscription::class)->findByFormation($formation);
            
            foreach($inscriptions as $inscription){
                $entityManager->remove($inscription);
                $entityManager->flush();
            }
            
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/formation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formation{% endblock %}

{% block body %}
<h1 align="center">Modifier une formation</h1><br>
<div class="container raw col-4" align="center">
    <div class="shadow-lg p-3 mb-5 bg-body rounded">
        {{ include('formation/_form.html.twig', {'button_label': 'Mise à jour'}) }}<br>
        {{ include('formation/_delete_form.html.twig') }}
    </div>
    <a href="{{ path('formation_index') }}">Retour à la liste</a>
</div>
{% endblock %}

templates/formation/employe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation{% endblock %}

{% block body %}
    <h1 align="center">Liste des formations</h1><br>

    <table class="table" align="center">
        <thead>
            <tr>
                <th>Date de début     </th>
                <th>Nombre d'heures     </th>
                <th>Département    </th>
                <th>Produit     </th>
                <th>Actions     </th>
            </tr>
        </thead>
        <tbody> 
        {% for formation in formations %}   
            <tr>
                <td>{{ formation.dateDebut ? formation.dateDebut|date('d-m-Y') : '' }}</td>
                <td>{{ formation.nbresHeures }}</td>
                <td>{{ formation.departement }}</td>
                <td>{{ formation.produit.libelle }}</td>
                <td>
                    <a href="{{ path('inscription_new', {'id': formation.id}) }}">S'inscrire</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}

            

    <table class="table" align="center">
        <thead>
        <h1 align="center">Liste des formations déjà inscrit</h1><br>
            <tr>
                <th>Statut    </th>
                <th>Departement</th>
                <th>Produit </th>
            </tr>
        </thead>
            {% for inscription in inscriptions %}
                <tr>
                    <td>{{ inscription.statut}}</td>
                    <td>{{ inscription.formation.departement }}</td>
                    <td>{{ inscription.formation.produit.libelle }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>
{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation index{% endblock %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
<a class="navbar-brand" href="#">Formation Master</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">  Formations</a>
        <a class="nav-link" href="http://localhost/symfony1/public/inscription/"> Liste des inscriptions</a>
        <a class="nav-link" href="http://localhost/symfony1/public/employe/">  Employes</a>

      </div>
    </div>
  </div>
</nav><br>
    <h1 align="center">Liste des formations</h1><br>

    <div class="container raw col-10" align="center">
        <table class="table shadow-lg p-3 mb-5 bg-body rounded" >
            <thead class="thead-dark">
                <tr>
                    <th>Date de début</th>
                    <th>Nombre d'heures</th>
                    <th>Département</th>
                    <th>Produit</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for formation in formations %}
                <tr>
                    <td>{{ formation.dateDebut ? formation.dateDebut|date('d-m-Y') : '' }}</td>
                    <td>{{ formation.nbresHeures }}</td>
                    <td>{{ formation.departement }}</td>
                    <td>{{ formation.produit.libelle }}</td>
                    <td>
                        <a href="{{ path('formation_show', {'id': formation.id}) }}">Voir</a>
                        <a href="{{ path('formation_edit', {'id': formation.id}) }}">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation{% endblock %}

{% block body %}
    <h1 align="center">Créer une nouvelle formation</h1><br>
    <div class="container" align="center">
        <div class="row col-4 shadow-lg p-3 mb-5 bg-body rounded" align="left">
            {{ include('formation/_form.html.twig') }}
            <a href="{{ path('inscription_index') }}"> Liste des inscriptions</a>
        </div>
    </div>
{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation{% endblock %}

{% block body %}
<h1 align="center">Formations</h1><br>
    <div class="container raw col-4" align="center">
        <table class="table shadow-lg p-3 mb-5 bg-body rounded">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ formation.id }}</td>
                </tr>
                <tr>
                    <th>Date de début</th>
                    <td>{{ formation.dateDebut ? formation.dateDebut|date('d-m-Y') : '' }}</td>
                </tr>
                <tr>
                    <th>Nombre d'heures</th>
                    <td>{{ formation.nbresHeures }}</td>
                </tr>
                <tr>
                    <th>Département</th>
                    <td>{{ formation.departement }}</td>
                </tr>
                <tr>
                    <th>Produit</th>
                    <td>{{ formation.produit.libelle }}</td>
                </tr>
            </tbody>
        </table>
    
        <a href="{{ path('formation_index') }}">Retour à la liste</a>

        <a href="{{ path('formation_edit', {'id': formation.id}) }}">Modifier</a>

        {{ include('formation/_delete_form.html.twig') }}
    </div>
{% endblock %}